sudo: true
language: ruby
services:
  - docker  
script:
  - docker-compose up --build -d
  - docker exec -t deno bash -c "deno run --allow-all --unstable generateData.ts"
#in frontend
  - docker exec -t node sh -c "npm run lint"
  - docker exec -t node sh -c "npm run test"
  - docker exec -t node sh -c "npm run build"
#in backend
  - docker exec -t deno bash -c "deno test --allow-all --unstable"
  - docker-compose down
