sudo: false
language: node_js
node_js:
  - 12
install:
- node -v
- curl -fsSL https://deno.land/x/install/install.sh | sh
- which deno
before_script:
 - cd client
 - npm ci
script:
#in frontend
- npm run lint
- npm run test
- npm run build
#in backend
# - cd ../
# - ./start.sh
#- deno fmt server/*.ts
#- deno fmt server/**/*.ts
# - deno test --allow-run --allow-net