sudo: false
language: node_js
services:
  - docker
before_script:
  - docker-compose up --build -d
script:
#in frontend
  - docker exec -it node bash
  - npm run lint
  - npm run test
  - npm run build
  - exit
#in backend
  - docker exec -it deno bash
  - deno test --allow-run --allow-net
  - exit