sudo: false
language: rust
rust:
  - 1.37.0
install:
- nvm install v12
- nvm use --delete-prefix v12
- node -v
- rustup component add rustfmt
- rustc --version
- cargo --version
- curl -fsSL https://deno.land/x/install/install.sh | sh
- export DENO_INSTALL="/home/travis/.deno"
- export PATH="$DENO_INSTALL/bin:$PATH"
before_script:
 - cd client
 - npm ci
script:
#in frontend
- npm run lint
- npm run test
- npm run build
#in backend
- cd ../server
- deno fmt server/*.ts
- deno fmt server/**/*.ts
- deno test server