sudo: true
language: ruby
services:
  - docker  
script:
  - docker-compose up --build -d
#in frontend
  - docker exec -t node bash -c "npm ci"
  - docker exec -t node bash -c "npm run lint"
  - docker exec -t node bash -c "npm run test"
  - docker exec -t node bash -c "npm run build"
#in backend
  - docker exec -t deno bash -c "deno test --allow-run --allow-net"
  - docker-compose down
