version: '3.7'

services: 
  deno:
    working_dir: /server-app
    container_name: deno
    build: 
      context: ./build/deno
      args: 
        - DENO_VERSION=v1.0.0-rc3
    # command: "deno run --allow-net --allow-read --allow-write --config=tsconfig.json index.ts"
    command: "denon index.ts"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.deno.rule=Host(`ucms.docker.localhost`) && PathPrefix(`/api`)"
      - "traefik.http.services.deno.loadbalancer.server.port=3000"
    volumes:
      - ./server:/server-app
  
  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
    ports: 
      - 8081:8081
  
  node:
    working_dir: /app-client
    container_name: node
    command: npm run start
    build:
      context: .
      dockerfile: ./build/node/Dockerfile
    environment: 
      - NODE_ENV=development
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node.rule=Host(`ucms.docker.localhost`)"
      - "traefik.http.services.node.loadbalancer.server.port=4200"
    volumes: 
      - ./client:/app-client 
      - /app-client/node_modules

  proxy:
    image: traefik:v2.2
    container_name: proxy
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "5000:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

